framework:
    default_locale: fr  # https://symfony.com/doc/current/translation.html
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:
            loco: # permet de se connecter à une API collaborative pour récupérer des traductions
                dsn: '%env(LOCO_DSN)%' #TODO a tester il faut configurer une clé API
