services:
  # service database qui aura pour nom portail-database
  database:
    image: mariadb:latest
    container_name: portail-database
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: portail_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # service phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portail-phpmyadmin
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8082:80"

  # service mailer
  mailer:
    image: axllent/mailpit
    container_name: portail-mailer
    ports:
      - "1025:1025" #SMTP
      - "8025:8025" #Web UI

volumes: # crée un volume persistant appelé db_data pour stocker les données de la base
  db_data:
